RULE_ID=15
RULE_NAME="中转"
RULE_ROLE="1"
SECURITY_LEVEL="standard"
LISTEN_PORT="50006"
LISTEN_IP="::"
THROUGH_IP="::"
REMOTE_HOST="103.219.195.4"
REMOTE_PORT="50006"
TLS_SERVER_NAME=""
WS_PATH=""
WS_HOST=""
RULE_NOTE=""
ENABLED="true"
CREATED_TIME="2026-04-30 02:19:01"

BALANCE_MODE="off"
TARGET_STATES=""
WEIGHTS=""

FAILOVER_ENABLED="false"
HEALTH_CHECK_INTERVAL="4"
FAILURE_THRESHOLD="2"
SUCCESS_THRESHOLD="2"
CONNECTION_TIMEOUT="3"

MPTCP_MODE="off"
PROXY_MODE="off"
