RULE_ID=5
RULE_NAME="中转"
RULE_ROLE="1"
SECURITY_LEVEL="standard"
LISTEN_PORT="19633"
LISTEN_IP="::"
THROUGH_IP="::"
REMOTE_HOST="147.90.235.56"
REMOTE_PORT="19633"
TLS_SERVER_NAME=""
WS_PATH=""
WS_HOST=""
RULE_NOTE=""
ENABLED="true"
CREATED_TIME="2026-05-07 17:14:04"

BALANCE_MODE="off"
TARGET_STATES=""
WEIGHTS=""

FAILOVER_ENABLED="false"
HEALTH_CHECK_INTERVAL="4"
FAILURE_THRESHOLD="2"
SUCCESS_THRESHOLD="2"
CONNECTION_TIMEOUT="3"

MPTCP_MODE="off"
PROXY_MODE="off"
