RULE_ID=1
RULE_NAME="中转"
RULE_ROLE="1"
SECURITY_LEVEL="standard"
LISTEN_PORT="11002"
LISTEN_IP="::"
THROUGH_IP="::"
REMOTE_HOST="209.33.173.71"
REMOTE_PORT="11002"
TLS_SERVER_NAME=""
WS_PATH=""
WS_HOST=""
RULE_NOTE=""
ENABLED="true"
CREATED_TIME="2026-06-08 12:46:41"

BALANCE_MODE="off"
TARGET_STATES=""
WEIGHTS=""

FAILOVER_ENABLED="false"
HEALTH_CHECK_INTERVAL="4"
FAILURE_THRESHOLD="2"
SUCCESS_THRESHOLD="2"
CONNECTION_TIMEOUT="3"

MPTCP_MODE="off"
PROXY_MODE="off"
